### ISSUE TITLE
Connect project to SonarQube

### ISSUE THREAD

**Issue by stefan2904** [krakenh2020/EduPilotPrototype1#1]
Although this is a demo project, I just tried to connect it to KRAKEN's SonarQube to make sure the pipeline works.

Unfortunately I don't have the permission to create a project in Sonar, so the scan [currently fails](https://github.com/krakenh2020/EduPilotPrototype1/runs/1494405511?check_suite_focus=true).
@gdegani, can you care one for me? I propose the name "EduPilotPrototype1". 

The [GitHub Actions plugin I use](https://github.com/kitabisa/sonarqube-action#usage) to interact with Sonar requires the following parameters: `projectBaseDir`, `projectKey`, `projectName` (the key is visible under *Project information*).

Let me know what else do you need.

I already created [a token for my account](https://sonari.atosresearch.eu/account/security/).

Thanks!

**Comment by stefan2904** [comment]
As an alternative, we can use Jenkins for this, but I don't have and permissions there. 

![image](https://user-images.githubusercontent.com/527767/101071302-b43d0400-359c-11eb-9be9-991e684c818e.png)

**Comment by gdegani** [comment]
For an account on Sonar or Jenkins you should ask to Sara.  
In the meantime I will try to integrate Sonar.

**Comment by stefan2904** [comment]
I have accounts on both systems, but the accounts don't have the permission to create projects ...

**Comment by gdegani** [comment]
Do you mind if I use edupilot-prototype1  as project key?

**Comment by gdegani** [comment]
Now the integration works. But there is something broken in sonarqube. We have to contact their support.

**Comment by stefan2904** [comment]
> Do you mind if I use edupilot-prototype1 as project key?

works for me.

> Now the integration works. But there is something broken in sonarqube. We have to contact their support.

Okay, let's hope it works next week. 
Good we tried it with something non-time-critical first. ;-)
